const CONTAINER_WIDTH = 1024;
const NUM_COLUMNS = 12;
const GUTTER_SIZE = 10;
const COLUMN_WIDTH = (CONTAINER_WIDTH - GUTTER_SIZE) / NUM_COLUMNS;

export {
  CONTAINER_WIDTH,
  NUM_COLUMNS,
  GUTTER_SIZE,
  COLUMN_WIDTH,
};
